### PR TITLE
Update to Pydantic 2.X

### PR DESCRIPTION
**Pull request by Lnaden**
All lesson material has been updated to Pydantic v2.

Added favicon

### CODE REVIEW

**Review by janash — COMMENTED** [review]
@Lnaden  - I'm not sure when I'll get the chance to look at this in-depth. I trust your update! Do you want an in-depth review?

Concerning updating the major version - should we make the Pydantic v1 version available as well, or are we 100% upgrading to Pydantic v2?

**Comment by Lnaden** [comment]
I don't need an in-depth review per-se, I more wanted to call attention to this before I go and have this published on the Education site.

> should we make the Pydantic v1 version available as well

Because the APIs differ quite substantially between v1 and v2, and many of the old v1 ways of doing things we would teach are deprecated or outright removed in v2, I think doing a full switch over is the correct choice here. Having gone through the whole rewrite of the pydantic parts now:

* It should only be ever so slightly harder for new people learning Pydantic compared to v1 because of the expanded power in v2 and likely not ever seeing the `Annotated` object in any meaningful way from `typing` or `typing_extensions`.
* It takes re-training yourself if you learned v1 which I think does have some barriers, especially if you've done lots of v1-style implementation in codes.

**Comment by Lnaden** [comment]
In short: if you're okay going to v2 solely, we can just merge this.

**Comment by janash** [comment]
okay, sounds good to me!

**Review by janash — APPROVED** [review]

**Pull request merged**
